name: Build and deploy

on: pull_request

jobs:
  first-test:
    runs-on: ubuntu-latest
    name: Testing
    steps:
      - name: Branch
        shell: bash
        run: echo ${GITHUB_HEAD_REF}
      - name: User
        shell: bash
        run: echo ${GITHUB_ACTOR}
