name: Build and deploy

on: pull_request

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build and push Docker image 
    steps:
      - name: Branch
        shell: bash
        run: echo ${GITHUB_HEAD_REF}
      - name: User
        shell: bash
        run: echo ${GITHUB_ACTOR}
      - name: Check out the Repository
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: srkiNZ84
          password: ${{ secrets.SRDAN_GH_TOKEN }}
          registry: docker.pkg.github.com
          repository: srkinz84/go-api-game/api-player
          tags: ${{ github.actor }}-${{ github.run_number }}
